[options]
addons_path = C:\project\odoo\odoo18\addons,C:\project\odoo\RoongtaERP\
admin_passwd = admin123

db_host = localhost
db_port = 5432
db_user = odoo
db_password = 1234
db_name = roongta_erp

logfile = C:\project\odoo\RoongtaERP\roongta.log
http_port = 9900
proxy_mode = False

limit_memory_soft = 268435456
limit_memory_hard = 536870912
limit_time_cpu = 60
limit_time_real = 120
workers = 0

# csv_internal_sep = ,
# data_dir = C:/Users/admin/AppData/Local/Odoo18/data
# data_dir = C:/Users/admin/AppData/Local/Odoo18/data/filestore/rv_enterprise


# python C:\project\odoo\odoo18 -c odoo.conf
# new database
# python C:\project\odoo\odoo18\odoo-bin -c odoo18.conf -d neotech -i base

# python C:\project\odoo\odoo18\odoo-bin -c C:\project\odoo\RoongtaERP\odoo.conf

